name: Test Github action for job processor

on:
  pull_request:
    branches: [ main, master, staging ]
  push:
    branches: [ main, master, staging ]

jobs: 
  test:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:3.4.23
        ports:
          - 27017:27017
      rabbitmq:
        image: rabbitmq:3.8
        env:
          RABBITMQ_DEFAULT_USER: guest
          RABBITMQ_DEFAULT_PASS: guest
        ports:
          - 5672

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name : Start cypress
        uses: cypress-io/github-action@v2   
        with:
          build: npm start